domain: "bingusdingus.github.io"
url: "https://bingusdingus.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "bingusdingus" # the name of your site, e.g. ACME Corp.
theme: null
